# Generated by Django 2.2 on 2019-09-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PMP_AUDIT_TESTING',
            fields=[
                ('Project_Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Comments', models.CharField(max_length=200, null=True)),
                ('Customer_Name', models.CharField(max_length=200, null=True)),
                ('Project_Year', models.IntegerField()),
                ('Assigned_To', models.CharField(max_length=200, null=True)),
                ('Current_Task_No', models.IntegerField()),
                ('Current_Task', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': '"PMP_AUDIT_TESTING"',
            },
        ),
    ]
